CREATE TABLE IF NOT EXISTS todos (
    id INTEGER NOT NULL AUTO_INCREMENT,
    userId VARCHAR(50) NOT NULL,
    description VARCHAR(50) NOT NULL,
    category VARCHAR(30) NOT NULL,
    isCompleted BOOLEAN NOT NULL,
    targetDate DATE NOT NULL,
    PRIMARY KEY (id)
)